---
  ## Needs to be previously unregistered
  - name: register to RHN
    command: /usr/bin/subscription-manager register --username={{ rhn_username }} --password={{ rhn_password }}
    ignore_errors: yes

  - name: Check status of registration
    shell: /usr/bin/subscription-manager list --consumed --matches="*Red Hat Satellite*" | awk '/Pool ID/ {print $3}' | head -1
    register: subscription_status

  - block:
    - name: remove all PoolIDs
      command: /usr/bin/subscription-manager remove --all

    - name: Get the PoolID for Satellite
      shell:  /usr/bin/subscription-manager list --all --available --matches="*Red Hat Satellite 6*" | awk '/Pool ID/ {print $3}' | head -1
      register: pool_id

    - name: Attach to the Satellite Pool
      command: /usr/bin/subscription-manager attach --pool={{ pool_id.stdout }}

    - name: Enable the Repos
      command: /usr/bin/subscription-manager repos --disable "*" --enable rhel-7-server-rpms --enable rhel-server-rhscl-7-rpms --enable rhel-7-server-satellite-6.2-rpms
    when: not subscription_status.stdout

  - name: Check status of registration
    shell: /usr/bin/subscription-manager list --consumed --matches="*Red Hat Satellite 6*" | awk '/Pool ID/ {print $3}' | head -1
    register: subscription_status

  - block:
    - name: Clear Yum Cache
      command: "{{ item }}"
      with_items:
        - "yum clean all"
        - "rm -rf /var/cache/yum/*"

    - name: Install Satellite
      yum: name="satellite" state=latest update_cache=yes

    - name: Install Puppet OpenSCAP package
      yum: name="puppet-foreman_scap_client" state=latest

    - name: template out the answers file
      template:
        src: satellite-answers.yaml.j2
        dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
        mode: 0644
      register: satellite_answers

    - name: Check if Satellite is installed
      stat: path=/var/www/html/pub/katello-ca-consumer-latest.noarch.rpm
      register: satelliteisinstalled

    - name: run the satellite installer
      command: satellite-installer --scenario satellite -v --foreman-admin-username stadmin --foreman-admin-password {{ rhn_password }}
      when: not satelliteisinstalled.stat.exists or satellite_answers.changed

    - name: Create Hammer directory
      file:
        path: /root/.hammer
        state: directory
        mode: 0700

    - name: Hammer config file
      template:
        src: cli_config.yml.j2
        dest: /root/.hammer/cli_config.yml

    - name: Config Satellite
      include: sat_conf.yml

    when: subscription_status.stdout
